"""
Step 3: PS Estimation
=====================
Identifies Persistent Scatterer (PS) candidate pixels and removes
Atmospheric Phase Screen (APS) noise using MintPy's time-series framework.

What are PS points?
  Pixels that remain stable reflectors across all images, e.g.
  rock outcrops, mine infrastructure, building corners, road surfaces.
  These are the reliable measurement points for deformation estimation.

What is APS?
  Atmospheric delay artifacts that look like deformation but aren't —
  caused by water vapour, ionosphere, etc. Must be removed.

Usage:
  python src/ps_estimation.py
  python src/ps_estimation.py --config config.yaml
"""

import os
import sys
import yaml
import logging
import argparse
import subprocess
from pathlib import Path

import numpy as np
import h5py
import matplotlib.pyplot as plt

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)


def load_config(path: str = "config.yaml") -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def write_mintpy_config(cfg: dict, mintpy_dir: Path) -> Path:
    """
    Write a MintPy smallbaselineApp.cfg configuration file.
    MintPy is the standard open-source tool for time-series InSAR analysis.
    https://mintpy.readthedocs.io/
    """
    mp_cfg = cfg.get("mintpy", {})
    aoi    = cfg["aoi"]
    bbox   = aoi["bbox"]
    ref    = mp_cfg.get("reference_lalo")
    atm    = mp_cfg.get("atm_correction", "pyaps")

    # Build config file content
    lines = [
        "# MintPy configuration — generated by PSInSAR mine pipeline",
        "",
        "########## 1. Load Data",
        f"mintpy.load.processor    = hyp3",
        f"mintpy.load.hyp3Dir      = {mintpy_dir / 'inputs'}",
        "",
        "########## 2. Reference",
    ]

    if ref:
        lines += [
            f"mintpy.reference.lalo    = {ref[0]}, {ref[1]}",
        ]
    else:
        lines += [
            "mintpy.reference.lalo    = auto  # automatic selection",
        ]

    lines += [
        "",
        "########## 3. Tropospheric Delay Correction (APS)",
        f"mintpy.troposphericDelay.method  = {atm}",
        "",
        "########## 4. Topographic Residuals",
        "mintpy.topographicResidual       = yes",
        "",
        "########## 5. Mask",
        f"mintpy.network.coherenceBased    = yes",
        f"mintpy.network.minCoherence      = {mp_cfg.get('min_coherence', 0.7)}",
        "",
        "########## 6. Temporal Coherence",
        f"mintpy.networkInversion.minTempCoh  = {mp_cfg.get('amplitude_dispersion_threshold', 0.7)}",
        "",
        "########## 7. Geocode",
        "mintpy.geocode                   = yes",
        f"mintpy.geocode.laloStep          = 0.0001,  -0.0001",
        f"mintpy.geocode.bbox              = {bbox[1]}, {bbox[0]}, {bbox[3]}, {bbox[2]}",
        "",
        "########## 8. Google Earth KMZ",
        "mintpy.save.kmz                  = yes",
    ]

    cfg_path = mintpy_dir / "smallbaselineApp.cfg"
    cfg_path.write_text("\n".join(lines))
    log.info(f" MintPy config written: {cfg_path}")
    return cfg_path


def run_mintpy_pipeline(cfg_path: Path, mintpy_dir: Path) -> None:
    """
    Run MintPy's full smallbaselineApp.py pipeline.
    Steps inside MintPy:
      1. load_data       → ifgramStack.h5
      2. modify_network  → drop bad pairs
      3. reference_point → choose stable reference
      4. quick_overview  → sanity check
      5. correct_unwrap_error → bridge phase jumps
      6. invert_network  → time-series displacement
      7. correct_LOD     → local oscillator drift
      8. correct_SET     → solid earth tides
      9. correct_troposphere → remove APS (atmospheric)
     10. deramp          → remove orbital ramp
     11. correct_topography → remove DEM error
     12. residual_RMS    → assess quality
     13. mask            → apply coherence mask
     14. geocode         → project to lat/lon
     15. google_earth    → export KMZ
     16. save_hdfeos5    → export to HDF-EOS5
    """
    log.info("Running MintPy smallbaselineApp.py (full PSInSAR pipeline)...")
    log.info("  This may take 10–60 minutes depending on stack size.")

    cmd = [
        "smallbaselineApp.py",
        str(cfg_path),
        "--dir", str(mintpy_dir),
        "--dostep", "load_data",
    ]

    # Run each MintPy step
    steps = [
        "load_data",
        "modify_network",
        "reference_point",
        "invert_network",
        "correct_troposphere",
        "deramp",
        "correct_topography",
        "residual_RMS",
        "mask",
        "geocode",
    ]

    for step in steps:
        log.info(f"  → MintPy step: {step}")
        result = subprocess.run(
            ["smallbaselineApp.py", str(cfg_path), "--dostep", step, "--dir", str(mintpy_dir)],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            log.error(f"  ✗ Step '{step}' failed:\n{result.stderr[-1000:]}")
            # Don't abort — log and continue; some steps may fail on incomplete data
        else:
            log.info(f" {step} complete")


def compute_amplitude_dispersion(mintpy_dir: Path, threshold: float = 0.25) -> np.ndarray:
    """
    Compute Amplitude Dispersion Index (ADI) to identify PS candidates.
    ADI = std(amplitude) / mean(amplitude)
    Lower ADI = more stable = better PS candidate.
    threshold = 0.25 is standard (Ferretti et al. 2001)
    """
    ifgram_stack = mintpy_dir / "inputs" / "ifgramStack.h5"
    if not ifgram_stack.exists():
        log.warning(f"ifgramStack.h5 not found at {ifgram_stack}")
        return None

    log.info("Computing Amplitude Dispersion Index (ADI) for PS candidate selection...")
    with h5py.File(ifgram_stack, "r") as f:
        # HyP3/MintPy stores amplitude in 'unwrapPhase' dataset context
        # Actual amplitude comes from the magnitude of the SLC stack
        # Here we use coherence as a proxy for PS quality
        if "coherence" in f:
            coh = f["coherence"][:]              # shape: (N_pairs, H, W)
            mean_coh = np.mean(coh, axis=0)
            std_coh  = np.std(coh, axis=0)
            # ADI proxy: use 1 - mean_coherence (lower = better PS)
            adi = std_coh / (mean_coh + 1e-6)
        else:
            log.warning("Coherence data not found in ifgramStack.h5")
            return None

    ps_mask = adi < threshold
    n_ps    = np.sum(ps_mask)
    density = n_ps / ps_mask.size * 100

    log.info(f"  ADI threshold: {threshold}")
    log.info(f"  PS candidates: {n_ps:,} pixels  ({density:.2f}% of total)")

    # Save PS mask
    mask_path = mintpy_dir / "ps_mask.npy"
    np.save(mask_path, ps_mask)
    log.info(f"  PS mask saved: {mask_path}")

    return ps_mask


def plot_adi_map(adi: np.ndarray, ps_mask: np.ndarray, output_dir: Path) -> None:
    """Visualize the ADI and PS candidate distribution."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    im0 = axes[0].imshow(adi, cmap="viridis", vmin=0, vmax=0.5)
    axes[0].set_title("Amplitude Dispersion Index (ADI)\nLower = Better PS Candidate")
    plt.colorbar(im0, ax=axes[0], label="ADI")

    axes[1].imshow(ps_mask, cmap="hot")
    axes[1].set_title(f"PS Candidate Pixels\n(ADI < 0.25, N={np.sum(ps_mask):,})")

    plt.tight_layout()
    out_path = output_dir / "adi_ps_map.png"
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close()
    log.info(f"  ADI map saved: {out_path}")


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="PSInSAR Step 3: PS Estimation")
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument("--skip-mintpy", action="store_true",
                        help="Skip MintPy execution (for testing)")
    args = parser.parse_args()

    cfg        = load_config(args.config)
    data_dir   = Path(cfg["output"]["data_dir"])
    mintpy_dir = data_dir / "mintpy_stack"
    output_dir = Path(cfg["output"]["results_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    mintpy_dir.mkdir(parents=True, exist_ok=True)

    # 3.1 Write MintPy configuration file
    cfg_path = write_mintpy_config(cfg, mintpy_dir)

    # 3.2 Run full MintPy pipeline (PS identification + APS correction)
    if not args.skip_mintpy:
        run_mintpy_pipeline(cfg_path, mintpy_dir)
    else:
        log.info("Skipping MintPy execution (--skip-mintpy flag set)")

    # 3.3 Compute ADI-based PS mask (additional quality check)
    mp_cfg    = cfg.get("mintpy", {})
    threshold = mp_cfg.get("amplitude_dispersion_threshold", 0.25)
    ps_mask   = compute_amplitude_dispersion(mintpy_dir, threshold)

    if ps_mask is not None:
        plot_adi_map(ps_mask, ps_mask, output_dir)

    log.info("\n PS ESTIMATION COMPLETE")
    log.info(f"   MintPy outputs: {mintpy_dir}")
    log.info("   Next step: python src/04_velocity_generation.py")


if __name__ == "__main__":
    main()